### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by sirishere** [Zedespook/Nimbus#13]
I get this : 

```

/home/elon/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void LagComp::CreateMove(CUserCmd*)’:
/home/elon/Nimbus/src/Hacks/lagcomp.cpp:62:13: error: conflicting declaration ‘const auto weapon’
   62 |  const auto weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |             ^~~~~~

```

**Comment by tzekid** [comment]
A longer error log:

```bash
[  3%] Building CXX object CMakeFiles/Fuzion.dir/src/Hacks/nofall.cpp.o
/home/kid/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void RemoveInvalidTicks()’:
/home/kid/Nimbus/src/Hacks/lagcomp.cpp:11:38: warning: comparison of integer expressions of different signedness: ‘std::vector<LagComp::LagCompTickInfo>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   11 |  while (LagComp::lagCompTicks.size() > Settings::LagComp::value)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kid/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void LagComp::CreateMove(CUserCmd*)’:
/home/kid/Nimbus/src/Hacks/lagcomp.cpp:62:13: error: conflicting declaration ‘const auto weapon’
   62 |  const auto weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |             ^~~~~~
/home/kid/Nimbus/src/Hacks/lagcomp.cpp:56:22: note: previous declaration as ‘C_BaseCombatWeapon* weapon’
   56 |  C_BaseCombatWeapon *weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |                      ^~~~~~
make[2]: *** [CMakeFiles/Fuzion.dir/build.make:600: CMakeFiles/Fuzion.dir/src/Hacks/lagcomp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/kid/Nimbus'
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/Fuzion.dir/all] Error 2
make[1]: Leaving directory '/home/kid/Nimbus'
make: *** [Makefile:101: all] Error 2
```

**Comment by slop-me** [comment]
Oh okay I'm not the only one. I just spent 3 and a half hours trying to fix this by using all sorts of different versions of GCC and G++ I'm having the same issue

**Comment by slop-me** [comment]
[ 11%] Building CXX object CMakeFiles/Fuzion.dir/src/Hooks/PumpWindowsMessageLoop.cpp.o
/home/hehe/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void RemoveInvalidTicks()’:
/home/hehe/Nimbus/src/Hacks/lagcomp.cpp:11:38: warning: comparison of integer expressions of different signedness: ‘std::vector<LagComp::LagCompTickInfo>::size_type’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   11 |  while (LagComp::lagCompTicks.size() > Settings::LagComp::value)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hehe/Nimbus/src/Hacks/lagcomp.cpp: In function ‘void LagComp::CreateMove(CUserCmd*)’:
/home/hehe/Nimbus/src/Hacks/lagcomp.cpp:62:13: error: conflicting declaration ‘const auto weapon’
   62 |  const auto weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |             ^~~~~~
/home/hehe/Nimbus/src/Hacks/lagcomp.cpp:56:22: note: previous declaration as ‘C_BaseCombatWeapon* weapon’
   56 |  C_BaseCombatWeapon *weapon = (C_BaseCombatWeapon *)entityList->GetClientEntityFromHandle(localplayer->GetActiveWeapon());
      |                      ^~~~~~
CMakeFiles/Fuzion.dir/build.make:1022: recipe for target 'CMakeFiles/Fuzion.dir/src/Hacks/lagcomp.cpp.o' failed

**Comment by tzekid** [comment]
> Oh okay I'm not the only one. I just spent 3 and a half hours trying to fix this by using all sorts of different versions of GCC and G++ I'm having the same issue

Have a look at [my change](https://github.com/tzekid/Nimbus/commit/9c39d86bff91a7c81401aa5535728cab70467d7a), that fixes it :)

**Comment by slop-me** [comment]
> > Oh okay I'm not the only one. I just spent 3 and a half hours trying to fix this by using all sorts of different versions of GCC and G++ I'm having the same issue
> 
> Have a look at [my change](https://github.com/tzekid/Nimbus/commit/9c39d86bff91a7c81401aa5535728cab70467d7a), that fixes it :)

Yup, thank you for that as soon as I saw the fix I applied it to a duplicate repository 😃

**Comment by acuifex** [comment]
boys, [linktocommit.mp4](https://github.com/Zedespook/Nimbus/commit/30f14d4bcd00c6d9e83970e21fe290d955be38e4)
